## Beautifulsoup
- we can use beautifulsoup to parse the data from html and xml file

In [1]:
!pip install beautifulsoup4 lxml

Requirement already satisfied: beautifulsoup4 in c:\users\shaya\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: lxml in c:\users\shaya\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\shaya\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\shaya\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)

In [2]:
from bs4 import BeautifulSoup

In [3]:
with open("books_html/page1.html") as f:
    content = f.read()

# content    # testing

In [4]:
soup = BeautifulSoup(content, "html.parser")

In [5]:
# soup # testing

In [6]:
h3s = soup.find_all("h3")

In [7]:
# h3s

In [8]:
# tag a has parameters href, title

# for h3 in  h3s:
#     # print(h3.find("a")["href"])   # testing for href
#     print(h3.find("a")["title"])     # testing for title

In [9]:
articles = soup.select("article.product_pod")

In [10]:
# articles

In [11]:
for article in articles:
    print(article)
    break

<article class="product_pod">
<div class="image_container">
<a href="a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [12]:
items = []

for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text.split("£")[1]
    stock = article.select_one("p.instock").text.strip()
    items.append([title, price, stock])
    print(title)
    print(price)
    print(stock)
    break

print(items)

A Light in the Attic
51.77
In stock
[['A Light in the Attic', '51.77', 'In stock']]

In [13]:
# for all books in page 1

items = []

for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text.split("£")[1]
    stock = article.select_one("p.instock").text.strip()
    rating_element = article.select_one("p.star-rating")
    ratings = rating_element["class"][1]
    items.append([title, price, ratings, stock])
    # print(ratings)
    # print(title)
    # print(price)
    # print(stock)
    # break

# print(items[:5])
# print(len(items))

In [14]:
import pandas as pd

books1_df = pd.DataFrame(items, columns=['Book Name', "Price", "Ratings", "Stock"])

In [15]:
books1_df.shape

(20, 4)

In [16]:
books1_df

                                            Book Name  Price Ratings     Stock
0                                A Light in the Attic  51.77   Three  In stock
1                                  Tipping the Velvet  53.74     One  In stock
2                                          Soumission  50.10     One  In stock
3                                       Sharp Objects  47.82    Four  In stock
4               Sapiens: A Brief History of Humankind  54.23    Five  In stock
5                                     The Requiem Red  22.65     One  In stock
6   The Dirty Little Secrets of Getting Your Dream...  33.34    Four  In stock
7   The Coming Woman: A Novel Based on the Life of...  17.93   Three  In stock
8   The Boys in the Boat: Nine Americans and Their...  22.60    Four  In stock
9                                     The Black Maria  52.15     One  In stock
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99     Two  In stock
11                              Shakespeare's Sonnets  20.66    Four  In stock
12                                        Set Me Free  17.46    Five  In stock
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29    Five  In stock
14                          Rip it Up and Start Again  35.02    Five  In stock
15  Our Band Could Be Your Life: Scenes from the A...  57.25   Three  In stock
16                                               Olio  23.88     One  In stock
17  Mesaerion: The Best Science Fiction Stories 18...  37.59     One  In stock
18                       Libertarianism for Beginners  51.33     Two  In stock
19                            It's Only the Himalayas  45.17     Two  In stock

In [17]:
books1_df.iloc[0:5,]

                               Book Name  Price Ratings     Stock
0                   A Light in the Attic  51.77   Three  In stock
1                     Tipping the Velvet  53.74     One  In stock
2                             Soumission  50.10     One  In stock
3                          Sharp Objects  47.82    Four  In stock
4  Sapiens: A Brief History of Humankind  54.23    Five  In stock

In [18]:
books1_df.to_csv("data.csv", index=False)